apiVersion: v1
name: keepalived-operator
version: 0.1.0
appVersion: 0.1.0
description: Helm chart that deploys keepalived-operator
keywords:
  - VIP
  - load balancer
sources:
  - https://github.com/redhat-cop/keepalived-operator
engine: gotpl