apiVersion: apps/v1
kind: Deployment
metadata:
  name: keepalived-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keepalived-operator
  template:
    metadata:
      labels:
        name: keepalived-operator
    spec:
      serviceAccountName: keepalived-operator
      containers:
        - name: keepalived-operator
          # Replace this with the built image name
          image: quay.io/redhat-cop/keepalived-operator:{{ .Values.image_tag }}
          command:
          - keepalived-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keepalived-operator"          
